version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trading_db
      - REDIS_URL=redis://redis:6379/0
      - MODEL_PATH=/app/models/trained_model
    depends_on:
      - db
      - redis
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      target: frontend-build
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
    command: npm run start

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 